
/* generated by irken-tdfa */

#include <stdint.h>
typedef struct {
  int8_t src;
  int8_t dst;
} insn;

insn uinsns[] = {
  {-2, 2},{-2, 3},{-1,-1},
  {-2, 0},{-2, 1},{-1,-1},
  {-2, 4},{-2, 5},{-1,-1},
  {-2, 6},{-2, 7},{-1,-1},
  {-2, 2},{-2, 1},{-1,-1},
  {-2, 0},{-2, 8},{6, 9},{2, 6},{0, 2},{9, 0},{8, 10},{1, 8},{10, 1},{3, 11},{5, 12},{7, 13},{-1,-1},
  {-2, 4},{-2, 3},{-1,-1},
  {-2, 6},{-2, 5},{-1,-1},
  {-2, 0},{-2, 7},{2, 9},{4, 2},{6, 4},{0, 6},{9, 0},{-1,-1},
  {-2, 14},{-2, 7},{-1,-1},
  {-2, 0},{-2, 1},{2, 9},{0, 2},{9, 0},{-1,-1},
  {-2, 2},{-2, 15},{-2, 8},{-1,-1},
  {-2, 0},{-2, 3},{-1,-1},
  {-2, 0},{-2, 1},{2, 9},{0, 2},{9, 0},{14, 4},{3, 8},{8, 13},{5, 11},{7, 12},{-1,-1},
  {-2, 2},{-2, 5},{-1,-1},
  {-2, 0},{-2, 1},{0, 2},{4, 0},{-1,-1},
  {-2, 4},{-2, 8},{-1,-1},
  {-2, 0},{-2, 11},{-1,-1},
  {-2, 0},{-2, 5},{-1,-1},
  {-2, 2},{-2, 1},{5, 8},{8, 12},{7, 11},{11, 13},{-1,-1},
  {-2, 4},{-2, 7},{-1,-1},
  {-2, 6},{-2, 8},{-1,-1},
  {-2, 2},{-2, 11},{-1,-1},
  {-2, 0},{-2, 12},{-1,-1},
  {-2, 0},{-2, 7},{-1,-1},
  {-2, 4},{-2, 1},{4, 9},{2, 4},{9, 2},{7, 8},{8, 11},{11, 12},{12, 13},{-1,-1},
  {-2, 2},{-2, 8},{-1,-1},
  {-2, 6},{-2, 11},{-1,-1},
  {-2, 4},{-2, 12},{-1,-1},
  {-2, 0},{-2, 13},{-2, 16},{-1,-1},
  {-2, 0},{-2, 1},{2, 4},{3, 10},{5, 3},{7, 5},{1, 7},{10, 1},{-1,-1},
  {-2, 0},{-2, 1},{6, 4},{1, 3},{8, 1},{-1,-1},
  {-2, 6},{-2, 3},{2, 9},{6, 2},{4, 6},{0, 4},{9, 0},{1, 13},{13, 12},{12, 11},{11, 8},{3, 1},{-1,-1},
  {-1,-1}};

typedef struct {
  int8_t tag;
  int8_t reg;
} tag;

tag utags[] = {
  {0, 0},{1, 15},{-1,-1},
  {2, 1},{3, 16},{-1,-1},
  {-1,-1}};

int finals[28] = {
  -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,
  -1,-1,-1,-1,-1,-1,3,-1};

typedef struct {
  unsigned int state;
  unsigned int vpos;
  unsigned int regs[17];
} tdfa_state;

void tdfa_search (
  tdfa_state * search,
  unsigned char * buffer,
  unsigned int buffer_len,
  unsigned int * start,
  void (*callback)(int, int, int)
)
{
  unsigned int i = *start;
  unsigned int final = 0;
  unsigned int state = search->state;
  unsigned int insns = 0;
  for(; i < buffer_len; i++) {
    unsigned char ch = buffer[i];
    switch (state) {
      case 0:
      if (ch>=48 && ch<58) {
        insns = 0;
        state = 1;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 1:
      if (ch>=48 && ch<58) {
        insns = 6;
        state = 2;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 2:
      if (ch>=48 && ch<58) {
        insns = 9;
        state = 3;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 3:
      if (ch==45) {
        insns = 12;
        state = 4;
      } else if (ch>=48 && ch<58) {
        insns = 15;
        state = 27;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 4:
      if (ch>=48 && ch<58) {
        insns = 28;
        state = 5;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 5:
      if (ch>=48 && ch<58) {
        insns = 31;
        state = 6;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 6:
      if (ch==45) {
        insns = 12;
        state = 7;
      } else if (ch>=48 && ch<58) {
        insns = 34;
        state = 3;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 7:
      if (ch>=48 && ch<58) {
        insns = 28;
        state = 8;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 8:
      if (ch>=48 && ch<58) {
        insns = 31;
        state = 9;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 9:
      if (ch>=48 && ch<58) {
        insns = 42;
        state = 10;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 10:
      if (ch==45) {
        insns = 45;
        state = 4;
      } else if (ch>=48 && ch<58) {
        insns = 51;
        state = 11;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 11:
      if (ch==45) {
        insns = 55;
        state = 12;
      } else if (ch>=48 && ch<58) {
        insns = 58;
        state = 27;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 12:
      if (ch>=48 && ch<58) {
        insns = 69;
        state = 13;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 13:
      if (ch>=48 && ch<58) {
        insns = 9;
        state = 14;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 14:
      if (ch==45) {
        insns = 72;
        state = 7;
      } else if (ch>=48 && ch<58) {
        insns = 77;
        state = 15;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 15:
      if (ch==45) {
        insns = 12;
        state = 4;
      } else if (ch>=48 && ch<58) {
        insns = 80;
        state = 16;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 16:
      if (ch==45) {
        insns = 83;
        state = 17;
      } else if (ch>=48 && ch<58) {
        insns = 86;
        state = 27;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 17:
      if (ch>=48 && ch<58) {
        insns = 93;
        state = 18;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 18:
      if (ch>=48 && ch<58) {
        insns = 96;
        state = 19;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 19:
      if (ch==45) {
        insns = 45;
        state = 7;
      } else if (ch>=48 && ch<58) {
        insns = 99;
        state = 20;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 20:
      if (ch==45) {
        insns = 12;
        state = 4;
      } else if (ch>=48 && ch<58) {
        insns = 102;
        state = 21;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 21:
      if (ch==45) {
        insns = 105;
        state = 22;
      } else if (ch>=48 && ch<58) {
        insns = 108;
        state = 27;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 22:
      if (ch>=48 && ch<58) {
        insns = 118;
        state = 23;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 23:
      if (ch>=48 && ch<58) {
        insns = 121;
        state = 24;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 24:
      if (ch==45) {
        insns = 72;
        state = 7;
      } else if (ch>=48 && ch<58) {
        insns = 124;
        state = 25;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 25:
      if (ch==45) {
        insns = 12;
        state = 4;
      } else if (ch>=48 && ch<58) {
        insns = 127;
        state = 26;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 26:
      if (ch==45) {
        insns = 131;
        state = 22;
      } else if (ch>=48 && ch<58) {
        insns = 12;
        state = 27;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
      case 27:
      if (ch==45) {
        insns = 140;
        state = 12;
      } else if (ch>=48 && ch<58) {
        insns = 146;
        state = 27;
      } else { 
        insns = 3;
        state = 0;
      }
      break;
    }
    while (1) {
      insn ti = uinsns[insns++];
      if (ti.src == -1) {
        break;
      } else if (ti.src == -2) {
        search->regs[ti.dst] = search->vpos + i + 1;
      } else {
        search->regs[ti.dst] = search->regs[ti.src];
      }
    }
    if (finals[state] != -1) {
      int fpos = finals[state];
      while (utags[fpos].tag != -1) {
        int group_num = utags[fpos].tag / 2;
        int start = search->regs[utags[fpos].reg];
        int stop = search->regs[utags[fpos+1].reg];
        callback (group_num, start, stop);
        fpos += 2;
      }
    }
  }
  search->state = state;
}
